version: "3.8"
services:
  evolution_api_test:
    image: atendai/evolution-api:v2.1.2
    container_name: evolution_api_test
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SERVER_URL=http://localhost:8081
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=TEST_KEY
      - DATABASE_ENABLED=false # Use SQLite (default)
      - CACHE_REDIS_ENABLED=false
      - LOG_LEVEL=DEBUG
    volumes:
      - evolution_test_data:/evolution/instances

volumes:
  evolution_test_data:
